language: node_js  
node_js:  
  - 5.0
  - 6.0
  - 7.0
script: node_modules/karma/bin/karma start ./karma.conf.js --singleRun  
before_install:  
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start